### ISSUE TITLE
چرا دانلود کروم؟

### ISSUE THREAD

**Issue by iaghapour** [mimshins/figma-backup#1]
دلیل اینکه میخاد کرومیوم رو دانلود کنه چیه؟
موقع نصب میره برای دانلود کرومیوم.

**Comment by mimshins** [comment]
سلام،
 از روبات [Puppeteer](https://pptr.dev/) استفاده می‌کنیم. این روبات از کرومیوم توی حال [Headless Mode](https://developers.google.com/web/updates/2017/04/headless-chrome) استفاده می‌کنه.
