### ISSUE TITLE
Feature Request: Add support to export in another format additionally

### ISSUE THREAD

**Issue by itb-devs-de** [mimshins/figma-backup#12]
Great project!
What I'm missing is a possibility to export files additionally in a different format, because if Figma goes down .fig files are of no use. So an additional export as Sketch, XD, PDF, or PNG files would be nice!

**Comment by mimshins** [comment]
@itb-devs-de 
Thanks for your feedback.
The thing is you can always convert your `.fig` files to any other formats using other third party applications.

For example:
Figma to sketch: [Magicul](https://magicul.io/converter/figma-to-sketch) | [Hypermatic/Figmatic](https://www.hypermatic.com/convertify/) | [Avocade](https://avocode.com/convert-figma-to-sketch)
