### ISSUE TITLE
Add `--only-modified-files` option to target only modified files

### ISSUE THREAD

**Issue by IgorLeSouverain** [mimshins/figma-backup#15]
Figma's API can show if a file was modified or not https://www.figma.com/developers/api#get-files-endpoint , based on that it would be very convenient if the script could download a file only if it was modified.

It also shows when a certain project was modified https://www.figma.com/developers/api#get-project-files-endpoint , but it works really weird because if I modify a file in a project, for some reason, it's not showing that the project was modified, so be ware of that, I already made a ticket about this problem, I hope they fix it.

Thanks.

**Comment by mimshins** [comment]
Closing the issue due to the project being archived.
