### ISSUE TITLE
Add an option to download projects by `teamId`

### ISSUE THREAD

**Issue by mimshins** [mimshins/figma-backup#16]
An example:

```bash
figma-backup 
  -e "example@gmail.com"
  -p "secretpassword"
  -t "secrettoken"
  --teams-ids "ID1" "ID2"
```

**Comment by amirnegah** [comment]
Dear Mostafa
How can I use this option?
I tried figma-backup --help and I couldn't see this option.
thanks
<img width="608" alt="image" src="https://user-images.githubusercontent.com/77375918/218316169-66b7e521-49a6-4b20-8257-d0d374d81e09.png">

**Comment by mimshins** [comment]
Hello there,
This is a feature request, we haven't implemented it yet.

**Comment by amirnegah** [comment]
Thanks for your answer
I have a problem and need help.
I've 6 Design and 4 FigJam files in my figma account. When I started the bot, it showed me every file and notified: File (filename) successfully downloaded. But in the final directory, I only have 4 FigJam files.
Could you help me please?
thanks :)

**Comment by mimshins** [comment]
Please open a new issue and provide information about your machine and package version so that I can help you further.

**Comment by mimshins** [comment]
Closing the issue due to the project being archived.
