### ISSUE TITLE
Add an option to specify download path for each project

### ISSUE THREAD

**Issue by mostafaznv** [mimshins/figma-backup#19]
Hello,

Thank you for developing this amazing package. I was wondering if it would be possible to add a feature that allows users to specify a download path for each project.

I am currently working on a small service that backs up all of my Figma projects, organizes them, and sends them to me via Telegram. However, the current folder structure splits the backups into multiple folders named with datetime, which makes it difficult to determine which backup belongs to which project.

Having the ability to specify a download path for each project would greatly enhance the organization and efficiency of my backup process.

Thank you in advance for your assistance.

**Comment by mimshins** [comment]
Hi there,
I will work on this option, thanks for your suggestion and considerations.

But there's a catch, you can only change the output's file structure... unfortunately `puppeteer` doesn't support an option to change the download path. (the `figma-backup-root` will always be in your terminal's current working directory)

**Comment by mimshins** [comment]
Closing the issue due to the project being archived.
