### ISSUE TITLE
Failed to launch the browser process! (linux problems)

### ISSUE THREAD

**Issue by sunnythaper** [mimshins/figma-backup#2]
First of all, I'm a newb designer just trying to get backups working so I may not fully understand my issue but I feel like this error is telling me I have a few more pre-reqs to install before this script works.

```
 / ___|_   _|/ \  |  _ \_   _|
 \___ \ | | / _ \ | |_) || |
  ___) || |/ ___ \|  _ < | |
 |____/ |_/_/   \_\_| \_\|_|


/usr/lib/node_modules/figma-backup/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:203
            reject(new Error([
                   ^

Error: Failed to launch the browser process!
/usr/lib/node_modules/figma-backup/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/usr/lib/node_modules/figma-backup/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:203:20)
    at Interface.<anonymous> (/usr/lib/node_modules/figma-backup/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:68)
    at Interface.emit (node:events:402:35)
    at Interface.close (node:internal/readline/interface:496:10)
    at Socket.onend (node:internal/readline/interface:229:10)
    at Socket.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

Node.js v17.2.0
root@figma:~#
```

For context this is a fresh install of Ubuntu in a virtualized environment. 

- First boot
- Apt update/upgrade
- Install nodejs
- Install npm
- Install figma-backup
- Run figma-backup-interactive
- Error

**Comment by sunnythaper** [comment]
After looking into this more, I discovered I was missing libnss3 specifically for this error so I apt installed that. After which I had the same situation come up for a few other apt installs. In the end I was able to install all the dependencies and it worked! Only issue is it gets to the download stage and times out cause I have so much to backup. Even setting the timeout via legacy and interactive doesn't seem to change the 30000ms default.

**Comment by mimshins** [comment]
Hello @sunnythaper,
Can you tell me the exact message you are getting for that timed out error, so I can investigate the issue?
Also please give me the full command (in legacy mode, with authentication parts being crossed out).

**Comment by lordunited** [comment]
Same issue here

**Comment by mimshins** [comment]
> Same issue here

Can you tell me the exact message you are getting and the full command (in legacy mode, with authentication parts being crossed out).

**Comment by lordunited** [comment]
> > Same issue here
> 
> Can you tell me the exact message you are getting and the full command (in legacy mode, with authentication parts being crossed out).

Error: Failed to launch the browser process!
[1218/171448.924313:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/usr/local/lib/node_modules/figma-backup/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:203:20)
    at Interface.<anonymous> (/usr/local/lib/node_modules/figma-backup/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:68)
    at Interface.emit (node:events:402:35)
    at Interface.close (node:internal/readline/interface:496:10)
    at Socket.onend (node:internal/readline/interface:229:10)
    at Socket.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

and the command is something like this :
figma-backup -e email -p password -t token --projects-ids projectid

**Comment by lordunited** [comment]
> > > Same issue here
> > 
> > 
> > Can you tell me the exact message you are getting and the full command (in legacy mode, with authentication parts being crossed out).
> 
> Error: Failed to launch the browser process! [1218/171448.924313:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
> 
> TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
> 
> ```
> at onClose (/usr/local/lib/node_modules/figma-backup/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:203:20)
> at Interface.<anonymous> (/usr/local/lib/node_modules/figma-backup/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:68)
> at Interface.emit (node:events:402:35)
> at Interface.close (node:internal/readline/interface:496:10)
> at Socket.onend (node:internal/readline/interface:229:10)
> at Socket.emit (node:events:402:35)
> at endReadableNT (node:internal/streams/readable:1343:12)
> at processTicksAndRejections (node:internal/process/task_queues:83:21)
> ```
> 
> and the command is something like this : figma-backup -e email -p password -t token --projects-ids projectid

--no-sandbox also doesnt make any changes.

**Comment by mimshins** [comment]
> > > > Same issue here
> > > 
> > > 
> > > Can you tell me the exact message you are getting and the full command (in legacy mode, with authentication parts being crossed out).
> > 
> > 
> > Error: Failed to launch the browser process! [1218/171448.924313:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
> > TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
> > ```
> > at onClose (/usr/local/lib/node_modules/figma-backup/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:203:20)
> > at Interface.<anonymous> (/usr/local/lib/node_modules/figma-backup/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:68)
> > at Interface.emit (node:events:402:35)
> > at Interface.close (node:internal/readline/interface:496:10)
> > at Socket.onend (node:internal/readline/interface:229:10)
> > at Socket.emit (node:events:402:35)
> > at endReadableNT (node:internal/streams/readable:1343:12)
> > at processTicksAndRejections (node:internal/process/task_queues:83:21)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and the command is something like this : figma-backup -e email -p password -t token --projects-ids projectid
> 
> --no-sandbox also doesnt make any changes.

Please try your command with `--debug` option appended and check if it fixes it.

**Comment by lordunited** [comment]
> > > > > Same issue here
> > > > 
> > > > 
> > > > Can you tell me the exact message you are getting and the full command (in legacy mode, with authentication parts being crossed out).
> > > 
> > > 
> > > Error: Failed to launch the browser process! [1218/171448.924313:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
> > > TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
> > > ```
> > > at onClose (/usr/local/lib/node_modules/figma-backup/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:203:20)
> > > at Interface.<anonymous> (/usr/local/lib/node_modules/figma-backup/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:68)
> > > at Interface.emit (node:events:402:35)
> > > at Interface.close (node:internal/readline/interface:496:10)
> > > at Socket.onend (node:internal/readline/interface:229:10)
> > > at Socket.emit (node:events:402:35)
> > > at endReadableNT (node:internal/streams/readable:1343:12)
> > > at processTicksAndRejections (node:internal/process/task_queues:83:21)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > and the command is something like this : figma-backup -e email -p password -t token --projects-ids projectid
> > 
> > 
> > --no-sandbox also doesnt make any changes.
> 
> Please try your command with `--debug` option appended and check if it fixes it.

I tried --debug . nothing changed. still get that error.

**Comment by mimshins** [comment]
@MohammadrezaMasoumi 
It seems that puppeteer has some issues on Linux Systems, it requires further investigation.
Thanks for your feedback, I'll investigate the issue.

**Comment by mimshins** [comment]
@MohammadrezaMasoumi 
I have release the patch.

Upgrade your local package by running:
`npm update -g figma-backup`
or
`yarn global upgrade figma-backup@^`

Please try to run the command again and check if the issue persists.

**Comment by lordunited** [comment]
> npm update -g figma-backup
  after update , i got this error
Error: Failed to launch the browser process!
[3478:3478:1219/113112.081258:ERROR:browser_main_loop.cc(1409)] Unable to open X display.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/usr/local/lib/node_modules/figma-backup/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:203:20)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/figma-backup/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:194:79)
    at ChildProcess.emit (node:events:402:35)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
/figma-backup# Error: Failed to launch the browser process!
[3478:3478:1219/113112.081258:ERROR:browser_main_loop.cc(1409)] Unable to open X display.

**Comment by mimshins** [comment]
> > npm update -g figma-backup
> > after update , i got this error
> > Error: Failed to launch the browser process!
> > [3478:3478:1219/113112.081258:ERROR:browser_main_loop.cc(1409)] Unable to open X display.
> 
> TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
> 
> ```
> at onClose (/usr/local/lib/node_modules/figma-backup/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:203:20)
> at ChildProcess.<anonymous> (/usr/local/lib/node_modules/figma-backup/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:194:79)
> at ChildProcess.emit (node:events:402:35)
> at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
> ```
> 
> /figma-backup# Error: Failed to launch the browser process! [3478:3478:1219/113112.081258:ERROR:browser_main_loop.cc(1409)] Unable to open X display.

Make sure all the necessary dependencies are installed. You can run `ldd chrome | grep not` on a Linux machine to check which dependencies are missing.

**Comment by sunnythaper** [comment]
Sorry for my delay in response, but I have started a brand new VM and installed the latest version of figma-backup (along with all dependencies mentioned in your README.md for Ubuntu) and I'm getting this:

```bash
/usr/bin/figma-backup -> /usr/lib/node_modules/figma-backup/lib/index.js
/usr/bin/figma-backup-interactive -> /usr/lib/node_modules/figma-backup/lib/index.interactive.js

> puppeteer@11.0.0 install /usr/lib/node_modules/figma-backup/node_modules/puppeteer
> node install.js

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/usr/lib/node_modules/figma-backup/node_modules/puppeteer/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@11.0.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@11.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-21T20_01_34_383Z-debug.log
```

When run `sudo npm install -g figma-backup`

For additional context, here are the commands I am running up until this point:

```
curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
sudo aptitude install nodejs npm
sudo aptitude install ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils
sudo npm install -g figma-backup
```

**Comment by sunnythaper** [comment]
For additional context, here are the commands I am running up until this point:

```
curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
sudo aptitude install nodejs npm
sudo aptitude install ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils
sudo npm install -g figma-backup
```

**Comment by lordunited** [comment]
> > > npm update -g figma-backup
> > > after update , i got this error
> > > Error: Failed to launch the browser process!
> > > [3478:3478:1219/113112.081258:ERROR:browser_main_loop.cc(1409)] Unable to open X display.
> > 
> > 
> > TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
> > ```
> > at onClose (/usr/local/lib/node_modules/figma-backup/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:203:20)
> > at ChildProcess.<anonymous> (/usr/local/lib/node_modules/figma-backup/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:194:79)
> > at ChildProcess.emit (node:events:402:35)
> > at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > /figma-backup# Error: Failed to launch the browser process! [3478:3478:1219/113112.081258:ERROR:browser_main_loop.cc(1409)] Unable to open X display.
> 
> Make sure all the necessary dependencies are installed. You can run `ldd chrome | grep not` on a Linux machine to check which dependencies are missing.

im using Docker for launching this app

**Comment by lordunited** [comment]
Error: Failed to launch the browser process!
[3357766:3357766:1224/002247.637657:ERROR:browser_main_loop.cc(1409)] Unable to open X display.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/usr/lib/node_modules/figma-backup/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:203:20)
    at ChildProcess.<anonymous> (/usr/lib/node_modules/figma-backup/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:194:79)
    at ChildProcess.emit (events.js:412:35)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
i launched the code in bare instead of docker and got this error.

**Comment by mimshins** [comment]
Well this can't be resolved easily, I highly recommend you to clone the project and follow the instructions on troubleshooting docs and try to resolve the issue on your machine.
Maybe later you can share your experience and solution with me or even Pull Request the issue.

PS: I have tested the bot on MacOS & Windows machines and there wasn't any issue.

**Comment by MohammadrezaMasoumi** [comment]
can you say your node version?

**Comment by lordunited** [comment]
> Well this can't be resolved easily, I highly recommend you to clone the project and follow the instructions on troubleshooting docs and try to resolve the issue on your machine. Maybe later you can share your experience and solution with me or even Pull Request the issue.
> 
> PS: I have tested the bot on MacOS & Windows machines and there wasn't any issue.

can you say your node version?

**Comment by mimshins** [comment]
> > Well this can't be resolved easily, I highly recommend you to clone the project and follow the instructions on troubleshooting docs and try to resolve the issue on your machine. Maybe later you can share your experience and solution with me or even Pull Request the issue.
> > PS: I have tested the bot on MacOS & Windows machines and there wasn't any issue.
> 
> can you say your node version?

I'm using the LTS version, but 14 should suffice.

**Comment by lordunited** [comment]
Yeap, my issue resovled by NAT container to Host NIC.
The root cause is about chrome launch in random port .
In docker run use -P
in docker compose use network_mode: host
Thanks mostafa jan.
