### ISSUE TITLE
Error in Figma backup using package - missing download command for specific project

### ISSUE THREAD

**Issue by mostafaznv** [mimshins/figma-backup#20]
Hi,
I have encountered an issue with this package while trying to back up a specific project. The package works fine with other projects, but with this one, I receive an error. The output is as follows:

```
 Starting the backup task...
> Authenticating the bot...
        . Bot successfully logged in.
        . Caching the cookies...
        . Looking for cached cookies...
        . Setting the cached cookies...
> Backing up the file(UI Design - Handoff)...
        . Setting the download behavior...
        > Saving a local copy of the file(UI Design - Handoff)...
                . Opening up the figma command palette...
                . Typing down the download command...
                ERR. Couldn't find the download command.
                . Execute the download command...
ERR. Backup failed | Protocol error (Input.dispatchKeyEvent): Session closed. Most likely the page has been closed.
> Stopping the bot...
```

**Comment by mostafaznv** [comment]
I believe the issue I reported earlier might be related to the network connection on my server. Therefore, I am going to close this issue for now. However, if the issue persists and it is not related to the network connection, I will reopen the issue.

Thank you for your attention to this matter.

**Comment by mostafaznv** [comment]
Hi again.

I tried this on another server with a good internet connection, but I was unsuccessful. I received various errors, including: 

- ERR. Backup failed | waiting for function failed: timeout 30000ms exceeded
- ERR. Couldn't find the download command.
- Backup failed | Protocol error (Input.dispatchKeyEvent): Session closed. Most likely the page has been closed ()

Is there a way to increase the timeout for page loads?

**Comment by kornide** [comment]
Our team had the same problem until we found out that the files in question, despite us having view permissions for them, additionally had copy restrictions on them (which is described [here](https://help.figma.com/hc/en-us/articles/360040045574-Restrict-copying-and-sharing-on-files)). If that's the case, downloading those files won't work, as the "Save local copy..." command will never be suggested in the command palette to begin with. Perhaps that might be your problem?

**Comment by mimshins** [comment]
This will be fix on the next release, this week.
(Related to the #23)
