### ISSUE TITLE
ERR. Backup failed | Request failed with status code 404

### ISSUE THREAD

**Issue by dima-demian** [mimshins/figma-backup#21]
Hey guys!
Installed the figma-backup, ran it and got a request failed with status code 404. Tried to look through the issues here, but found nothing related with that one. Also, used --debug. It opens, authorizes successfully and then just closes with no result. Could help me with that? Any ideas where I should dig in to?

Thanks! Appreciate your work and assistance on the issue!

>  Starting the backup task...
> Authenticating the bot...
	. Bot successfully logged in.
	. Caching the cookies...
	. Looking for cached cookies...
	. Setting the cached cookies...
  ◡ > Fetching the project(Archive) files...ERR. Backup failed | Request failed with status code 404
> Stopping the bot...
  ◠ > Fetching the project(Archive) files...

**Comment by mimshins** [comment]
Hey there,
A 404 error indicates that the page does not exist. Based on the description you gave, the problem may be with the provided 'projectId' or the permissions of the project or its content.
