### ISSUE TITLE
Option to specify backup rotation

### ISSUE THREAD

**Issue by sas1024** [mimshins/figma-backup#22]
Hi!
Thank you for for very useful tool.

For now we have this directories layout for backup:
```
└── backups/
    └── [ISOStringifiedDate]/
```

I have a suggestion - the ability to specify backup rotation rules (for example, keep the last 2 backups, and delete the older ones).
Or, for example, the ability to remove saving to a [ISOStringifiedDate] directory from backup path.

**Comment by mimshins** [comment]
The option to specify download path for each project (#19) will be added to the bot on the next release.
But the rotation rules you just mentioned isn't actually part of the bot itself. Developers can write their own scripts to manage/manipulate the directories once the job is done.

**Comment by sas1024** [comment]
@mimshins any news about next release?
