### ISSUE TITLE
Files are not being saved

### ISSUE THREAD

**Issue by 0xRapid** [mimshins/figma-backup#26]
Hiya! I am using windows 10, installed it using NPM.

I am using the command where you do it manually with all the creds. It says it saved the files, but it does not save it to any folder.

Anyway to run it in debug mode and understand what's going on?

![image](https://github.com/mimshins/figma-backup/assets/14364861/afc7acc5-d15c-4c3a-bfe1-6d01aceee585)

**Comment by mimshins** [comment]
Hi there,
There is problems at the moment. I have some changes made but didn't have the chance to merge the changes.
To debug and feedback:
`figma-backup --debug`

**Comment by vivalenta** [comment]
Hi. Same error
![Screenshot from 2024-03-20 17-56-39](https://github.com/mimshins/figma-backup/assets/12153871/2ecd9089-ee23-4de8-b344-70dd5ba2a600)

**Comment by mimshins** [comment]
Closing the issue due to the project being archived.
