### ISSUE TITLE
work only with --debug

### ISSUE THREAD

**Issue by rickyticky2** [mimshins/figma-backup#28]
![image](https://github.com/mimshins/figma-backup/assets/79316032/8b9f5a17-e95a-4715-aac1-ac2524c42a68)

increased timeouts. Did not help.
await page.waitForFunction(
       () => !document.querySelector('[class*="progress_bar--outer"]'), { timeout: 90000 }
     );

But in debug mode everything works

**Comment by rickyticky2** [comment]
Tried it on MacOS

and on Ubuntu 18 + docker

in the second option - I get (with debug opt)

![image](https://github.com/mimshins/figma-backup/assets/79316032/95976ad5-a704-4b47-847b-5ce4843a6b89)

**Comment by rickyticky2** [comment]
Ubuntu 18 + docker without debug option - I get the same thing as on MacOs without debug -
![image](https://github.com/mimshins/figma-backup/assets/79316032/01042e8b-da12-4ee8-ac01-72992a202f01)

**Comment by mimshins** [comment]
Closing the issue due to the project being archived.
