### ISSUE TITLE
backup error (ERR. Backup failed | File with id "XXXXXXX" page loading failed!)

### ISSUE THREAD

**Issue by vgoltsev** [mimshins/figma-backup#29]
Recently an error appeared when downloading a file. In this case, the authorization is successful, it moves to the file successfully, and it is at the input of the context menu where we enter the command “save local copy” that the error appears. At the same time, manual backup using Figma works successfully. 
We tried to roll back six months and start using a different account. Does not help.
Help me please.

**Comment by github-user14** [comment]
@mimshins 
We have the same issue 🙁
Running on macOS 12.7.4

Would be awesome if you could take a look. Maybe its a quick fix for you 😇

**Comment by mimshins** [comment]
Closing the issue due to the project being archived.
