### ISSUE TITLE
i logged in with google in figma and i dont have any password

### ISSUE THREAD

**Issue by peyman-hakemi** [mimshins/figma-backup#4]
i logged in with google in Figma and i don't have any password to enter in backup process what should i do when interface want a password from me?

**Comment by mimshins** [comment]
@peyman-hakemi 
You have to generate a password for your Figma account.

To do that:
1- Logout from your account
2- Press the Forgot Password
3- Enter the GMail associated with your account
4- Follow the instructions

Voilà, you might have a password now ^^
