### ISSUE TITLE
backup procces will stopped every time because of 403

### ISSUE THREAD

**Issue by peyman-hakemi** [mimshins/figma-backup#5]
i am using this command 

figma-backup -e peyman.far@gmail.com -p 'myPassword' -t 'mySecretKey' --projects-ids 9FOKHeV9u6VwWYkPkX2WZA

with project id that i toke from this url
https://www.figma.com/file/9FOKHeV9u6VwWYkPkX2WZA/Su-Ui-process-(Copy)?node-id=81%3Ad40

> Starting the backup task...
> Authenticating the bot...
        . Bot successfully logged in.
        . Caching the cookies...
        . Looking for cached cookies...
        . Restoring the cached cookies...
  / > Fetching the project(9FOKHeV9u6VwWYkPkX2WZA) files...> Stopping the bot...

this is the proccec and this is the error i give 

BackupError: Backup failed | Request failed with status code 403

in my experience i used a vpn that open the android studio site in this case my vpn shouldn't have any problem with sanctions

**Comment by mimshins** [comment]
This issue isn't related to the Bot; It is related to the Figma itself. Are you sure that you have the right permissions to access that project?
By the way, the file you are trying to backup isn't a valid project, that's just a file.
`Figma Backup Bot` can't backup files that are not part of a valid project. It takes Project Ids and will backup the files inside of those projects.

**Comment by mimshins** [comment]
If you want to backup that file, you can easily download it yourself:
1- Press `cmd + p` (on Mac) or `ctrl + p` (on Windows) to open up the Command Palette.
2- Enter the `Save local copy` command

**Comment by peyman-hakemi** [comment]
i have viewer permission in a project, i duplicated that project and then saved it in my team project and now i am the owner of that project in my Figma.
then i opened the designs that i duplicated and copied the https://www.figma.com/file/****KiA59R5Zv4yOqCKIAqq0Ca****/Su-Ui-process?node-id=2672%3A26506 texts inside of **** in this url as project id (KiA59R5Zv4yOqCKIAqq0Ca)
is this the project ID? or is something else?
and if i was wrong in this scenario please let me know how can fix this problem

**Comment by mimshins** [comment]
You can't get the project id in the File View.
Go back one step and you will find yourself on Project View which has a URL similar to "https://www.figma.com/files/project/PROJECT_ID/PROJECT_NAME?fuid=PROJECT_HASH".
From there you might need to copy the `PROJECT_ID` part of the URL.

Let me know if you resolved the issue.

**Comment by pepijnverburg** [comment]
Thanks, was using the wrong ID as well. Now it is working very nicely. Well done on the project!

**Comment by mimshins** [comment]
> Thanks, was using the wrong ID as well. Now it is working very nicely. Well done on the project!

I'm glad it helped! ^^
